# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kprompt < Formula
  desc "AI CLI to control Kubernetes with natural language"
  homepage "https://kprompt.ai"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.0/kprompt_0.12.0_darwin_amd64.tar.gz"
      sha256 "375b1090d8fb97d74c880f1034e8d089caa4cd221ce31dff911e1d8f12069142"

      define_method(:install) do
        bin.install "kprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.0/kprompt_0.12.0_darwin_arm64.tar.gz"
      sha256 "8e462906b4d7cc29e3a14389dbb8ca51ff07591737b854018f118b202ce0a295"

      define_method(:install) do
        bin.install "kprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.0/kprompt_0.12.0_linux_amd64.tar.gz"
      sha256 "02b3cb624db65edf65de685349ded83f844a0aa3748f27b0e1b9cd38b1ab278e"
      define_method(:install) do
        bin.install "kprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.0/kprompt_0.12.0_linux_arm64.tar.gz"
      sha256 "f496bd64d71a05542a46115c4f05f9670b9a02fe9d2f6c2341b59736c794e9d2"
      define_method(:install) do
        bin.install "kprompt"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kprompt version")
  end
end
