# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kprompt < Formula
  desc "AI CLI to control Kubernetes with natural language"
  homepage "https://kprompt.ai"
  version "0.12.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.2/kprompt_0.12.2_darwin_amd64.tar.gz"
      sha256 "633a2fdfa8ce462fe46cb4dadfca92a7061bfaadd5057679d1656540e7cafb05"

      define_method(:install) do
        bin.install "kprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.2/kprompt_0.12.2_darwin_arm64.tar.gz"
      sha256 "c3c126d324451186d828ee95a93b202b843304aa51c0d659a828c4756e3bf359"

      define_method(:install) do
        bin.install "kprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.2/kprompt_0.12.2_linux_amd64.tar.gz"
      sha256 "3f44d7e902e063d4323b947a640a05127f0957ba4bf92eb9b41ab6e1431a45c8"
      define_method(:install) do
        bin.install "kprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kprompt/kprompt/releases/download/v0.12.2/kprompt_0.12.2_linux_arm64.tar.gz"
      sha256 "f20426117c8ead57d716ed028fd6fbf2163eb93d972af53daf2ea9aed642ac32"
      define_method(:install) do
        bin.install "kprompt"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kprompt version")
  end
end
